version: "3.8"

services:
  app:
    build: ./
    container_name: script-eval
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    depends_on:
      - app
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - app
      - prometheus
      - grafana
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
