version: "3.8"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: "keycloak"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH}
      KC_PROXY: ${KC_PROXY}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/script-evaluation-realm.json:/opt/keycloak/data/import/script-evaluation-realm.json


  app:
    build: ./
    container_name: script-eval
    restart: always
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_JWK_SET_URI: ${KEYCLOAK_JWK_SET_URI}
      KEYCLOAK_OPENID_CONFIG_URL: ${KEYCLOAK_OPENID_CONFIG_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    depends_on:
      - app
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_SERVE_FROM_SUB_PATH: ${GF_SERVER_SERVE_FROM_SUB_PATH}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - app
      - prometheus
      - grafana
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/custom_404.html:/usr/share/nginx/html/custom_404.html"
