version: "3.8"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: "keycloak"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: "/auth"
    command:
      - "start-dev"
      - "--import-realm"
      - "--proxy=edge"
      - "--hostname-strict=false"
    volumes:
      - ./keycloak/script-evaluation-realm.json:/opt/keycloak/data/import/script-evaluation-realm.json


  app:
    build: ./
    container_name: script-eval
    restart: always
    depends_on:
      - keycloak
    env_file:
      - "security.env"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    depends_on:
      - app
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
      - "GF_SERVER_ROOT_URL=http://localhost:8080/grafana/"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - app
      - prometheus
      - grafana
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/custom_404.html:/usr/share/nginx/html/custom_404.html"
