spring:
  task:
    execution:
      pool:
        max-size: 2
        core-size: 2
        queue-capacity: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
server:
  compression:
    enabled: true
    mime-types: text/plain
    min-response-size: 1KB
  forward-headers-strategy: framework
  port: 8081

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true
      scopes: api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true

