spring:
  task:
    execution:
      pool:
        max-size: 2
        core-size: 2
        queue-capacity: 5
server:
  compression:
    enabled: true
    mime-types: text/plain
    min-response-size: 1KB
  forward-headers-strategy: framework
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true

